import asyncio
import os
import sys

# Thêm thư mục gốc vào sys.path để import
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from src.agent.graph import run_clinical_agent

async def main():
    print("=== Test 1: First question ===")
    q1 = "Tôi bị mụn viêm đỏ ở má, có nên dùng benzoyl peroxide không?"
    print(f"User: {q1}")
    result1 = await run_clinical_agent(message=q1)
    
    print("\nStandalone question generated by agent:", result1.get("standalone_question", "N/A"))
    print("\nAnswer 1:\n", result1.get("answer"))
    
    
    print("\n\n=== Test 2: Follow-up question with ambiguous keyword ===")
    q2 = "Vậy loại đó có tác dụng phụ gì?"
    print(f"User: {q2}")
    
    history = [
        {"role": "user", "content": q1},
        {"role": "assistant", "content": result1.get("answer", "")}
    ]
    
    result2 = await run_clinical_agent(message=q2, conversation_history=history)
    print("\nStandalone question generated by agent (EXPECTED TO CONTAIN BENZOYL PEROXIDE):", result2.get("standalone_question", "N/A"))
    print("\nAnswer 2:\n", result2.get("answer"))
    
    
    print("\n\n=== Test 3: Another follow-up question ===")
    q3 = "Nếu da tôi bị khô thì sao?"
    print(f"User: {q3}")
    
    history.append({"role": "user", "content": q2})
    history.append({"role": "assistant", "content": result2.get("answer", "")})
    
    result3 = await run_clinical_agent(message=q3, conversation_history=history)
    print("\nStandalone question generated by agent:", result3.get("standalone_question", "N/A"))
    print("\nAnswer 3:\n", result3.get("answer"))

if __name__ == "__main__":
    asyncio.run(main())
